# Generated by Django 3.2.9 on 2021-11-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productowner', '0002_client_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='teste',
        ),
    ]
