# Generated by Django 3.2.9 on 2021-11-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_resume', models.CharField(max_length=50)),
                ('comment1', models.CharField(max_length=50)),
                ('comment2', models.CharField(max_length=50)),
                ('product_informations', models.CharField(max_length=200)),
                ('reasons_to_buy', models.CharField(max_length=200)),
            ],
        ),
    ]
