# Generated by Django 3.2.9 on 2021-11-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='photo',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m%Y'),
        ),
    ]
