# Generated by Django 3.2.9 on 2021-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211123_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='comment1',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='comment2',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_resume',
            field=models.CharField(max_length=150),
        ),
    ]
