# Generated by Django 3.2.9 on 2021-11-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20211123_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
